# Generated by Django 2.0.4 on 2018-04-24 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entity',
            options={'verbose_name': "Назва об'єкту"},
        ),
    ]
