# Generated by Django 2.0.4 on 2018-04-24 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_auto_20180424_1628'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entity',
            options={'verbose_name': "Назва об'єкту", 'verbose_name_plural': "Об'єкти"},
        ),
        migrations.AlterField(
            model_name='entity',
            name='name',
            field=models.CharField(max_length=100, verbose_name="Назва об'єкту"),
        ),
    ]
