# Generated by Django 2.0.4 on 2018-04-24 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_auto_20180424_1632'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категорія', 'verbose_name_plural': 'Категорії'},
        ),
        migrations.AlterModelOptions(
            name='document',
            options={'verbose_name': 'Документ', 'verbose_name_plural': 'Документи'},
        ),
        migrations.AlterModelOptions(
            name='entity',
            options={'verbose_name': "Об'єкт", 'verbose_name_plural': "Об'єкти"},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукти'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Працівник', 'verbose_name_plural': 'Працівники'},
        ),
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=200, verbose_name='Назва категорії'),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_name',
            field=models.CharField(max_length=100, verbose_name='Назва документу'),
        ),
        migrations.AlterField(
            model_name='document',
            name='edit_flag',
            field=models.CharField(choices=[('так', '1'), ('ні', '0')], default='t', max_length=3, verbose_name='Можливість редагувати'),
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Артикул'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=200, verbose_name='Назва продукту'),
        ),
        migrations.AlterField(
            model_name='user',
            name='f_name',
            field=models.CharField(max_length=50, verbose_name="Ім'я"),
        ),
        migrations.AlterField(
            model_name='user',
            name='l_name',
            field=models.CharField(max_length=50, verbose_name='Прізвище'),
        ),
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.CharField(max_length=100, verbose_name='Посада'),
        ),
    ]
