# Generated by Django 2.0.4 on 2018-04-24 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_auto_20180424_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='edit_flag',
            field=models.CharField(choices=[('yes', '1'), ('no', '0')], default='yes', max_length=3, verbose_name='Можливість редагувати'),
        ),
    ]
