# Generated by Django 2.0.4 on 2018-04-24 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0005_auto_20180424_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='edit_flag',
            field=models.CharField(choices=[('1', 'так'), ('0', 'ні')], default='1', max_length=3, verbose_name='Можливість редагувати'),
        ),
    ]
