# Generated by Django 2.0.4 on 2018-04-30 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0006_auto_20180424_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentlines',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
