# Generated by Django 2.0.4 on 2018-04-30 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0007_documentlines_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('шт.', 'шт.'), ('кг.', 'кг.')], max_length=1),
        ),
    ]
