# Generated by Django 2.0.4 on 2018-05-03 08:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('report', '0009_auto_20180430_1604'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=50, verbose_name="Ім'я")),
                ('l_name', models.CharField(max_length=50, verbose_name='Прізвище')),
                ('position', models.CharField(max_length=100, verbose_name='Посада')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='report.Entity')),
            ],
            options={
                'verbose_name': 'Працівник',
                'verbose_name_plural': 'Працівники',
            },
        ),
        migrations.RemoveField(
            model_name='user',
            name='entity',
        ),
        migrations.AlterField(
            model_name='document',
            name='edit_flag',
            field=models.CharField(choices=[('1', 'так'), ('0', 'ні')], default='0', max_length=3, verbose_name='Можливість редагувати'),
        ),
        migrations.AlterField(
            model_name='document',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
