# Generated by Django 2.0.5 on 2018-05-07 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0012_auto_20180507_1116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='edit_flag',
        ),
    ]
